<?php
namespace RamseyAws\CloudSearch;

use RamseyAws\AwsClient;

/**
 * This client is used to interact with the **Amazon CloudSearch** service.
 *
 * @method \RamseyAws\Result buildSuggesters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise buildSuggestersAsync(array $args = [])
 * @method \RamseyAws\Result createDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDomainAsync(array $args = [])
 * @method \RamseyAws\Result defineAnalysisScheme(array $args = [])
 * @method \GuzzleHttp\Promise\Promise defineAnalysisSchemeAsync(array $args = [])
 * @method \RamseyAws\Result defineExpression(array $args = [])
 * @method \GuzzleHttp\Promise\Promise defineExpressionAsync(array $args = [])
 * @method \RamseyAws\Result defineIndexField(array $args = [])
 * @method \GuzzleHttp\Promise\Promise defineIndexFieldAsync(array $args = [])
 * @method \RamseyAws\Result defineSuggester(array $args = [])
 * @method \GuzzleHttp\Promise\Promise defineSuggesterAsync(array $args = [])
 * @method \RamseyAws\Result deleteAnalysisScheme(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAnalysisSchemeAsync(array $args = [])
 * @method \RamseyAws\Result deleteDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDomainAsync(array $args = [])
 * @method \RamseyAws\Result deleteExpression(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteExpressionAsync(array $args = [])
 * @method \RamseyAws\Result deleteIndexField(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteIndexFieldAsync(array $args = [])
 * @method \RamseyAws\Result deleteSuggester(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSuggesterAsync(array $args = [])
 * @method \RamseyAws\Result describeAnalysisSchemes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAnalysisSchemesAsync(array $args = [])
 * @method \RamseyAws\Result describeAvailabilityOptions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAvailabilityOptionsAsync(array $args = [])
 * @method \RamseyAws\Result describeDomains(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDomainsAsync(array $args = [])
 * @method \RamseyAws\Result describeExpressions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeExpressionsAsync(array $args = [])
 * @method \RamseyAws\Result describeIndexFields(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeIndexFieldsAsync(array $args = [])
 * @method \RamseyAws\Result describeScalingParameters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeScalingParametersAsync(array $args = [])
 * @method \RamseyAws\Result describeServiceAccessPolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeServiceAccessPoliciesAsync(array $args = [])
 * @method \RamseyAws\Result describeSuggesters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeSuggestersAsync(array $args = [])
 * @method \RamseyAws\Result indexDocuments(array $args = [])
 * @method \GuzzleHttp\Promise\Promise indexDocumentsAsync(array $args = [])
 * @method \RamseyAws\Result listDomainNames(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDomainNamesAsync(array $args = [])
 * @method \RamseyAws\Result updateAvailabilityOptions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAvailabilityOptionsAsync(array $args = [])
 * @method \RamseyAws\Result updateScalingParameters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateScalingParametersAsync(array $args = [])
 * @method \RamseyAws\Result updateServiceAccessPolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateServiceAccessPoliciesAsync(array $args = [])
 */
class CloudSearchClient extends AwsClient {}
