<?php
namespace RamseyAws\MTurk;

use RamseyAws\AwsClient;

/**
 * This client is used to interact with the **Amazon Mechanical Turk Requester Service** service.
 * @method \RamseyAws\Result acceptQualificationRequest(array $args = [])
 * @method \GuzzleHttp\Promise\Promise acceptQualificationRequestAsync(array $args = [])
 * @method \RamseyAws\Result approveAssignment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise approveAssignmentAsync(array $args = [])
 * @method \RamseyAws\Result associateQualificationWithWorker(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateQualificationWithWorkerAsync(array $args = [])
 * @method \RamseyAws\Result createAdditionalAssignmentsForHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAdditionalAssignmentsForHITAsync(array $args = [])
 * @method \RamseyAws\Result createHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createHITAsync(array $args = [])
 * @method \RamseyAws\Result createHITType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createHITTypeAsync(array $args = [])
 * @method \RamseyAws\Result createHITWithHITType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createHITWithHITTypeAsync(array $args = [])
 * @method \RamseyAws\Result createQualificationType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createQualificationTypeAsync(array $args = [])
 * @method \RamseyAws\Result createWorkerBlock(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createWorkerBlockAsync(array $args = [])
 * @method \RamseyAws\Result deleteHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteHITAsync(array $args = [])
 * @method \RamseyAws\Result deleteQualificationType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteQualificationTypeAsync(array $args = [])
 * @method \RamseyAws\Result deleteWorkerBlock(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteWorkerBlockAsync(array $args = [])
 * @method \RamseyAws\Result disassociateQualificationFromWorker(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateQualificationFromWorkerAsync(array $args = [])
 * @method \RamseyAws\Result getAccountBalance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAccountBalanceAsync(array $args = [])
 * @method \RamseyAws\Result getAssignment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAssignmentAsync(array $args = [])
 * @method \RamseyAws\Result getFileUploadURL(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getFileUploadURLAsync(array $args = [])
 * @method \RamseyAws\Result getHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getHITAsync(array $args = [])
 * @method \RamseyAws\Result getQualificationScore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getQualificationScoreAsync(array $args = [])
 * @method \RamseyAws\Result getQualificationType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getQualificationTypeAsync(array $args = [])
 * @method \RamseyAws\Result listAssignmentsForHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAssignmentsForHITAsync(array $args = [])
 * @method \RamseyAws\Result listBonusPayments(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listBonusPaymentsAsync(array $args = [])
 * @method \RamseyAws\Result listHITs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listHITsAsync(array $args = [])
 * @method \RamseyAws\Result listHITsForQualificationType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listHITsForQualificationTypeAsync(array $args = [])
 * @method \RamseyAws\Result listQualificationRequests(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listQualificationRequestsAsync(array $args = [])
 * @method \RamseyAws\Result listQualificationTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listQualificationTypesAsync(array $args = [])
 * @method \RamseyAws\Result listReviewPolicyResultsForHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listReviewPolicyResultsForHITAsync(array $args = [])
 * @method \RamseyAws\Result listReviewableHITs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listReviewableHITsAsync(array $args = [])
 * @method \RamseyAws\Result listWorkerBlocks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkerBlocksAsync(array $args = [])
 * @method \RamseyAws\Result listWorkersWithQualificationType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkersWithQualificationTypeAsync(array $args = [])
 * @method \RamseyAws\Result notifyWorkers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise notifyWorkersAsync(array $args = [])
 * @method \RamseyAws\Result rejectAssignment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise rejectAssignmentAsync(array $args = [])
 * @method \RamseyAws\Result rejectQualificationRequest(array $args = [])
 * @method \GuzzleHttp\Promise\Promise rejectQualificationRequestAsync(array $args = [])
 * @method \RamseyAws\Result sendBonus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise sendBonusAsync(array $args = [])
 * @method \RamseyAws\Result sendTestEventNotification(array $args = [])
 * @method \GuzzleHttp\Promise\Promise sendTestEventNotificationAsync(array $args = [])
 * @method \RamseyAws\Result updateExpirationForHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateExpirationForHITAsync(array $args = [])
 * @method \RamseyAws\Result updateHITReviewStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateHITReviewStatusAsync(array $args = [])
 * @method \RamseyAws\Result updateHITTypeOfHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateHITTypeOfHITAsync(array $args = [])
 * @method \RamseyAws\Result updateNotificationSettings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateNotificationSettingsAsync(array $args = [])
 * @method \RamseyAws\Result updateQualificationType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateQualificationTypeAsync(array $args = [])
 */
class MTurkClient extends AwsClient {}
